apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
- name: mywp-pass
  literals:
  - password=redhat
resources:
  - rbac.yml
  - storage.yml
  - mysql.yml
  - wordpress.yml
