apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: <Give your encrypted password>


# To encrypt password 

#  using cmd echo -n 'mysql1234' | base64


  
